name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04

    outputs:
      skip_deploy: ${{ steps.check_skip.outputs.skip }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Linter
        run: npm run lint
        env:
          CI: true

      - name: Run Tests
        run: npm test
        env:
          CI: true

      - name: Build App
        run: npm run build

      - name: Set SKIP_TAG_DEPLOY
        id: check_skip
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            git log -1 --pretty=%B | grep -q "#skip" && echo "skip=true" >> $GITHUB_OUTPUT || echo "skip=false" >> $GITHUB_OUTPUT
          fi
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to Render
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
        if: ${{ github.event_name != 'pull_request' && steps.check_skip.outputs.skip != 'true' }}

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    if: ${{ github.event_name != 'pull_request' && needs.simple_deployment_pipeline.outputs.skip_deploy != 'true' }}

    steps:
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
